title: Digital Humanities Sam Hu
email: kuangyi.hu@tufts.edu
description: >- # this means to ignore newlines until "baseurl:"
  Hi! This is Sam's personal site for digital humanties
baseurl: "/dh_samhu" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  reg223


theme: minima
plugins:
  - jekyll-feed
  
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
